version: '3.8'

services:
  # MySql Database
  db:
    image: mysql:8.0.40
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: SchoolSystem
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - school-network

  # Java API
  backend:
    build: ./Back-End
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/SchoolSystem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - school-network

  # Angular Front-End
  frontend:
    build: ./Front-End 
    ports:
      - "4201:4201" 
    depends_on:
      - backend
    networks:
      - school-network

volumes:
  db_data:

networks:
  school-network:
    driver: bridge